-- 코드를 작성해주세요
/*
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
WHERE A.ITEM_ID NOT IN (B.PARENT_ITEM_ID) 
ORDER BY A.ITEM_ID DESC;
NULL 쓰라는 거 같은데.... 어따쓰지 */ 

/* 
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
WHERE A.ITEM_ID NOT IN (B.PARENT_ITEM_ID) AND B.PARENT_ITEM_ID IS NOT NULL
ORDER BY A.ITEM_ID DESC; 
얘도 아니네*/


SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE B.PARENT_ITEM_ID IS NULL
ORDER BY A.ITEM_ID DESC;


/*
NOT EXISTS
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
WHERE NOT EXISTS (
    SELECT 1
    FROM ITEM_TREE B2
    WHERE B2.PARENT_ITEM_ID = A.ITEM_ID
)
ORDER BY A.ITEM_ID DESC;
*/