-- 코드를 작성해주세요
/*
SELECT PARENT_ID AS ID, COUNT(ID) AS CHILD_COUNT
FROM ECOLI_DATA 
WHERE PARENT_ID IS NOT NULL
GROUP BY PARENT_ID
ORDER BY ID;
*/

/*
SELECT P.PARENT_ID AS ID, COUNT(E.ID) AS CHILD_COUNT
FROM ECOLI_DATA P LEFT JOIN ECOLI_DATA E ON P.ID = E.PARENT_ID
WHERE P.PARENT_ID IS NOT NULL
GROUP BY P.PARENT_ID
ORDER BY P.PARENT_ID;
*/


/*
SELECT P.ID, COUNT(E.PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA P
LEFT JOIN ECOLI_DATA E ON P.ID = E.PARENT_ID
WHERE E.PARENT_ID IS NOT NULL
GROUP BY P.ID
ORDER BY P.ID;
*/


SELECT P.ID, COUNT(E.PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA P
LEFT JOIN ECOLI_DATA E ON P.ID = E.PARENT_ID
GROUP BY P.ID
ORDER BY P.ID;