-- 코드를 작성해주세요
/*
SELECT ID, 
     PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS COLONY_NAME
FROM (SELECT ID, SIZE_OF_COLONY
      FROM ECOLI_DATA
      ORDER BY SIZE_OF_COLONY DESC
     ) AS E
ORDER BY ID;
*/
SELECT ID, 
       CASE 
           WHEN COLONY_NAME * 100 <= 25 THEN 'CRITICAL'
           WHEN COLONY_NAME * 100 <= 50 THEN 'HIGH'
           WHEN COLONY_NAME * 100 <= 75 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS COLONY_NAME
FROM (
    SELECT ID, 
           PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_NAME
    FROM ECOLI_DATA
) AS PER
ORDER BY ID;