-- 코드를 입력하세요
-- i.JOINED 가 2021 인 회원들 - CTE
-- o.테이블에 있는 COUNT(ONLINE_SALE_ID) / CTE
-- 비율 계산시 ROUND(컬럼, 1)까지
-- 정렬 YEAR, MONTH
WITH SIGN_IN AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT YEAR(s.SALES_DATE), 
    MONTH(s.SALES_DATE), 
    COUNT(DISTINCT s.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT s.USER_ID) / (SELECT COUNT(*) FROM SIGN_IN), 1) AS PURCHASED_RATIO
FROM SIGN_IN n JOIN ONLINE_SALE s ON n.USER_ID = s.USER_ID
GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE)
ORDER BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE);

