-- 코드를 입력하세요
/* SELECT HISTORY_ID, 
    CASE WHEN DIFF_DATE(A.END_DATE, A.START_DATE) >= 90
         THEN A.DAILY_FEE * 
         WHEN DIFF_DATE(A.END_DATE, A.START_DATE) >= 30
         THEN ?
         WHEN DIFF_DATE(A.END_DATE, A.START_DATE) >= 7
         THEN ?
         ELSE ?
         END AS FEE
FROM (CAR_RENTAL_COMPANY_CAR C INNER JOIN
      CAR_RENTAL_COMPANY_HISTORY H ON C.CAR_ID = H.CAR_ID) A INNER JOIN
      CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON A.CAR_TYPE = P.CAR_TYPE
WHERE A.CAR_TYPE = '트럭' &&
GROUP BY A.CAR_HISTORY
HAVING ?
ORDER BY FEE DESC, HISTORY_ID DESC; */

WITH VALUE AS (
    SELECT CAR.DAILY_FEE, CAR.CAR_TYPE, HISTORY.HISTORY_ID,
           DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
           CASE 
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
             ELSE '' 
           END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
    INNER JOIN CAR_RENTAL_COMPANY_CAR AS CAR ON CAR.CAR_ID = HISTORY.CAR_ID
    WHERE CAR.CAR_TYPE = '트럭')

SELECT VALUE.HISTORY_ID, 
    ROUND(VALUE.DAILY_FEE * VALUE.PERIOD * 
          (100 - IFNULL(PLAN.DISCOUNT_RATE,0)) / 100) AS FEE
FROM VALUE
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN 
    ON PLAN.DURATION_TYPE = VALUE.DURATION_TYPE 
    AND PLAN.CAR_TYPE = VALUE.CAR_TYPE
ORDER BY 2 DESC, 1 DESC