-- 제일 많이 작성한 사람
-- SUM 리뷰가 MAX인사람 LEVEL1 CTE
-- 조인
WITH BEST_REVIEWER AS (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_CNT DESC
    LIMIT 1
)
SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW r 
JOIN BEST_REVIEWER b ON r.MEMBER_ID = b.MEMBER_ID
JOIN MEMBER_PROFILE p ON b.MEMBER_ID = p.MEMBER_ID
ORDER BY r.REVIEW_DATE;