-- 코드를 작성해주세요
/*SELECT 
    YEAR,
    (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM (
    SELECT 
        ID,
        SIZE_OF_COLONY,
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS MAX_SIZE
        FROM ECOLI_DATA
) AS TEMP
ORDER BY YEAR ASC, YEAR_DEV ASC;*/
SELECT 
    EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
    (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM (
    SELECT 
        ID,
        SIZE_OF_COLONY,
        DIFFERENTIATION_DATE,
        MAX(SIZE_OF_COLONY) OVER (PARTITION BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)) AS MAX_SIZE
    FROM ECOLI_DATA
) AS TEMP
ORDER BY YEAR, YEAR_DEV;