-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT * FROM FIRST_HALF WHERE TOTAL_ORDER > 3000) A
INNER JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
WHERE B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC;