-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (
    SELECT MAX(A2.LENGTH)
    FROM FISH_INFO A2
    WHERE A2.FISH_TYPE = A.FISH_TYPE
)
ORDER BY A.ID;